
spring:
  profiles:
    active: dev
  application:
    name: notification-service

server:
  port: 0


---
spring:
  config:
    activate:
      on-profile:
        - dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  boot:
    admin:
      client:
        url: http://localhost:9090
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    appname: notification-service

---
spring:
  config:
    activate:
      on-profile:
        - test
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  boot:
    admin:
      client:
        enabled: false
eureka:
  client:
    enabled: false
